version: '3.8'

services:
  franchise-api:
    image: 367553824468.dkr.ecr.us-east-1.amazonaws.com/franquicias-api-repo:latest
    build: .
    container_name: franchise-reactive-api
    ports:
      - "8080:8080"
    restart: always